# Generated by Django 4.2.10 on 2024-04-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=254)),
                ('receiver_email', models.EmailField(max_length=254)),
                ('reference', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('send_date', models.DateTimeField()),
                ('status', models.CharField(max_length=8)),
                ('type', models.CharField(max_length=7)),
            ],
        ),
    ]
