# Generated by Django 4.2.10 on 2024-04-22 23:20

from django.db import migrations, models
import django.utils.timezone

seed_exchange_rates = "INSERT INTO payapp_exchangerates (from_currency, to_currency, conversion_rate) VALUES ('USD','GBP', 0.81), ('GBP','USD', 1.23), ('EUR','GBP', 0.86), ('GBP','EUR', 1.16), ('USD','EUR', 0.94), ('EUR','USD', 1.06)"

unseed_exchange_rates = ""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('conversion_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_currency', models.CharField(max_length=3)),
                ('sender_amount', models.FloatField()),
                ('receiver_email', models.EmailField(max_length=254)),
                ('receiver_currency', models.CharField(max_length=3)),
                ('receiver_amount', models.FloatField()),
                ('reference', models.CharField(max_length=50)),
                ('send_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=8)),
                ('type', models.CharField(max_length=7)),
            ],
        ),

        migrations.RunSQL(sql=seed_exchange_rates, reverse_sql=unseed_exchange_rates)
    ]
